version: '3.7'
services:
  frontend:    
    image: frontend
    ports:
      - 8081:8080
    depends_on:
      - backend
  backend:
    image: backend
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - 8000:8000